"""Product-facing persistence models and repositories."""

from docker_agent.persistence.adapter import (
    PersistedAgentTurn,
    persist_langgraph_turn,
)
from docker_agent.persistence.agent_config import (
    AgentConfigurationAlreadyExists,
    AgentConfigurationNotFound,
    AgentConfigurationRecord,
    create_agent_configuration,
    get_agent_configuration,
    list_agent_configurations,
    update_agent_configuration,
    validate_agent_configuration_settings,
)
from docker_agent.persistence.chat import (
    ChatConversationMismatch,
    ConversationAgentTypeMismatch,
    PersistentChatCoordinator,
    PersistentChatTurn,
)
from docker_agent.persistence.store import (
    ConversationNotFound,
    ConversationRecord,
    ConversationSnapshot,
    ExecutionRecord,
    MessageNotFound,
    MessageRecord,
    append_message,
    create_conversation,
    delete_conversation,
    get_conversation,
    init_persistence_store,
    list_conversations,
    load_conversation,
    rename_conversation,
    save_execution,
)
from docker_agent.persistence.telemetry import (
    AgentRunNotFound,
    AgentRunRecord,
    AgentRunStateError,
    AgentRunSummary,
    create_agent_run,
    finalize_agent_run_failure,
    finalize_agent_run_success,
    get_agent_run,
    list_agent_runs,
    safe_error_message,
    summarize_agent_runs,
)

__all__ = [
    "AgentConfigurationAlreadyExists",
    "AgentConfigurationNotFound",
    "AgentConfigurationRecord",
    "AgentRunNotFound",
    "AgentRunRecord",
    "AgentRunStateError",
    "AgentRunSummary",
    "ChatConversationMismatch",
    "ConversationAgentTypeMismatch",
    "ConversationNotFound",
    "ConversationRecord",
    "ConversationSnapshot",
    "ExecutionRecord",
    "MessageNotFound",
    "MessageRecord",
    "PersistedAgentTurn",
    "PersistentChatCoordinator",
    "PersistentChatTurn",
    "append_message",
    "create_agent_configuration",
    "create_agent_run",
    "create_conversation",
    "delete_conversation",
    "finalize_agent_run_failure",
    "finalize_agent_run_success",
    "get_agent_configuration",
    "get_agent_run",
    "get_conversation",
    "init_persistence_store",
    "list_agent_configurations",
    "list_agent_runs",
    "list_conversations",
    "load_conversation",
    "persist_langgraph_turn",
    "rename_conversation",
    "safe_error_message",
    "save_execution",
    "summarize_agent_runs",
    "update_agent_configuration",
    "validate_agent_configuration_settings",
]
